trigger:
  branches:
    include:
      - adf_publish 
  paths:
    exclude:
      - /devops-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
