CREATE TABLE dbo.Sales (
  RowId INT NOT NULL IDENTITY(1,1)
, Retailer NVARCHAR(255) NOT NULL
, SalesMonth DATE NOT NULL
, Product NVARCHAR(255) NOT NULL
, SalesValueUSD DECIMAL(19,2) NOT NULL
, UnitsSold INT NOT NULL
, RunSeqNo INT NOT NULL
, CONSTRAINT PK__dbo_Sales PRIMARY KEY (RowId)
);
